### ISSUE TITLE
How the repository is laid out

### ISSUE THREAD

**Issue by javierponferradalopez** [javierponferradalopez/local-semantic-search#12]
Part of #1

## Question

How is the repository laid out, and how does someone run it?

**Read first:** "The api-scaffolding structure" (#5) and "Which store holds the vectors" (#8).

**Decide:**

- One repository with a backend folder and a frontend folder, or a workspace tool such as pnpm workspaces or Turborepo? The owner's rule is "deliberately small", so the bar for a workspace tool is high.
- Where does shared TypeScript live — the API request and response types the frontend needs? Duplicated, generated, or a shared package?
- What does `docker compose` contain? Only the store, or the backend too? Someone clones this repo for a portfolio — how many commands until it runs?
- Where do the model weights live? Transformers.js downloads them on first use. Is that acceptable, or are they vendored or pre-fetched? What is the first-run experience and how long does it take?
- Where do uploaded files live on disk, and is that folder ignored by git?
- One Biome configuration or two? One TypeScript configuration or two?
- What scripts exist, and what does the README tell a stranger to type first?
- What runs in CI, if anything?

**Comment by javierponferradalopez** [comment]
## Resolution — how the repository is laid out

**A pnpm workspace of three packages, a backend split by capability, and Docker holding nothing but the store.** The bounded-context split is recorded as [ADR-0003](https://github.com/javierponferradalopez/local-semantic-search/blob/master/docs/adr/0003-two-contexts-share-one-glossary.md).

### 1. The shape

```
/
├── pnpm-workspace.yaml
├── biome.json                  one config for the whole tree
├── CONTEXT.md  docs/
├── contract/                   types only, no runtime code, no build step
├── frontend/                   React, Vite, shadcn/ui
└── backend/
    ├── docker-compose.yml      Postgres + pgvector, and nothing else
    ├── data/                   git-ignored in full
    │   ├── resources/          the stored Files — a stand-in for S3
    │   └── models/             the model weights
    └── src/
        ├── api/                HTTP edge, no business logic
        └── core/
            ├── cross-cutting/  Vector, TextEmbedder, ImageEmbedder + adapters
            ├── ingestion/      domain / use-cases / infrastructure
            └── search/         domain / use-cases / infrastructure
```

**pnpm, not npm.** The objection to a workspace was hoisting: npm would lift `node_modules` to the root and move the Transformers.js cache away from where the backend looks for it. pnpm does not hoist — its default `node_modules` is isolated and symlinked — so the objection does not apply.

**`contract/` is types only.** It ships TypeScript source rather than compiled JavaScript, so Vite and `tsx` consume it directly and there is no build step, no task order and no cache — which is what made a workspace expensive in the first place. The moment a validation function enters, the package stops being free. Node reinforces the rule: it refuses to run TypeScript inside `node_modules`, and a types-only package is erased at compile time so the file is never loaded.

**Three packages, not two.** `frontend` importing types from `backend` was rejected on the direction of the arrow: it would make the browser package depend on the package that carries Express, Drizzle and Transformers.js. Type-only imports are erased, but the dependency edge survives, and one slip has Vite resolving something that must never reach the browser.

### 2. The backend splits by capability, not by layer

`core/` is `ingestion/` and `search/` — the two acts of the business, and the two units the map's specs are cut into. The full reasoning, and what holds the boundary, is [ADR-0003](https://github.com/javierponferradalopez/local-semantic-search/blob/master/docs/adr/0003-two-contexts-share-one-glossary.md). In short: the two share one glossary, so the usual language test says one context, but the split is kept because the business has two capabilities. `search/` never imports `Resource` — [#9](https://github.com/javierponferradalopez/local-semantic-search/issues/9) made `Result` and `Match` read models, so it asks for rows. The shared kernel holds only `Vector` and the two embedder ports.

A flat `core/{domain,use-cases,infrastructure}` was proposed and rejected by the owner: the contexts must reflect the business.

### 3. Docker holds the store, and only the store

The compose file lives in `backend/`, because Docker is the backend's business and the frontend has none of it.

**Why the backend stays native.** On macOS a container runs inside a Linux VM. The 56 ms per image that decided SigLIP2 in [#7](https://github.com/javierponferradalopez/local-semantic-search/issues/7) were measured natively; containerised, that number degrades and stops meaning what it meant. A layout decision must not silently invalidate a closed one. Behind that: the weights would need a named volume or every `docker compose down -v` re-downloads them, the owned folder would need a bind mount, and `tsx watch` would become a reload inside a container.

**The framing that settles the data folders** — from the owner: the arrangement simulates a real deployment. Postgres in Docker stands in for a database server, so its data lives in a **named volume** and the application never touches those files. A bind mount to `backend/data/postgres/` was rejected for that reason, and on the facts: small constant writes through the macOS VM file share are slow, and the container's user collides with host permissions.

`backend/data/resources/` stands in for S3. **That makes the file store a port, not scattered `fs` calls**: `FileStore` in `domain/services/`, `FilesystemFileStore` in infrastructure, and `S3FileStore` replacing it one day without touching the domain. The Resource record stores a **key**, not an absolute path — which is both what S3 returns and what [ADR-0001](https://github.com/javierponferradalopez/local-semantic-search/blob/master/docs/adr/0001-postgres-with-pgvector-as-the-single-store.md) asked for when it said the stored path never resolves outside its folder.

**Starting clean is two commands, not one**, because there are two owners: `docker compose down -v` for the database, `rm -rf backend/data/resources/*` for the Files. Doing only the first leaves an empty list on screen and the copies still on disk. The README says so.

The backend creates `data/resources` at boot with `mkdir -p`. This is not decoration: [#10](https://github.com/javierponferradalopez/local-semantic-search/issues/10) copies the File before any work starts, so on a fresh clone the first upload would fail.

### 4. The model weights live in a folder the repo owns

**`backend/data/models/`, pinned with `env.cacheDir`.** The default is `./node_modules/@huggingface/transformers/.cache/`, which under pnpm resolves into the virtual store at `node_modules/.pnpm/@huggingface+transformers@<version>/…`. That path carries the version, so a library bump re-downloads everything. Same trap [#4](https://github.com/javierponferradalopez/local-semantic-search/issues/4) hit with the OCR model.

**And an explicit download script, because of a decision already closed.** The measured sizes: SigLIP2 base/16 `fp32` is **1129.5 MB of text tower plus 371.8 MB of vision tower — about 1.5 GB**, before whatever [#14](https://github.com/javierponferradalopez/local-semantic-search/issues/14) adds. Cold load is dominated by the download (47 s for SigLIP1, 63 s for CLIP); warm load from disk is 1.7 s. [#10](https://github.com/javierponferradalopez/local-semantic-search/issues/10) made the upload request **wait**, with no queue and no progress bar. Download on first use therefore means the first upload hangs for minutes with nothing on screen — it does not look like a download, it looks broken. The script moves that cost to where the user expects it: installation.

Vendoring the weights was rejected — 1.5 GB needs LFS, and GitHub's free quota is 1 GB.

Scope note: **where the bytes live and who fetches them** is this ticket. **When the model is loaded into memory and how it stays warm** is [#15](https://github.com/javierponferradalopez/local-semantic-search/issues/15).

### 5. Tooling

**One `biome.json` at the root.** Two configs would only let the quote style diverge between halves of one project. The house style ported from [#5](https://github.com/javierponferradalopez/local-semantic-search/issues/5) — single quotes, `{foo}` with no inner space, no trailing commas, 90 columns, blank line before `return`, type-only imports — with the known loss that Biome cannot enforce the type-aware rules.

**One `tsconfig.json` per package, no shared base.** The owner's call. The backend targets Node without `DOM`, the frontend the browser with JSX, and Vite's template generates three files of its own that would extend nothing of ours — leaving `backend` and a barely-compiling `contract` as the only real consumers of a base.

**`typescript@7` for checking, `tsx` for running.** These are not alternatives: `tsx` is a runner that strips types with esbuild and checks nothing; TypeScript's Go port is the checker. And the port is no longer a preview — **`typescript@7.0.2` is the published `latest`**, binary still `tsc`, so `@typescript/native-preview` (stuck at `7.0.0-dev`) is not needed. `tsc --noEmit` in `typecheck` is now native.

**Node 24 could run the backend with no runner at all** — `node --watch src/api/main.ts` works on 24.11. It was considered and dropped in favour of `tsx`. Recorded because it will be asked again: native Node **erases** types, it does not transform them, so `enum`, `namespace` and parameter properties need `--experimental-transform-types`, decorators are unsupported outright, and relative imports must carry the `.ts` extension.

**No decorators, and no `enum`.** A hand-written `Map` container instead of `typedi`, and Zod at the HTTP edge instead of `class-validator`. The reason is specific to `tsx`: **esbuild does not implement `emitDecoratorMetadata`**, so the decorators run but the reflected design types never exist. `typedi`'s implicit injection and `class-transformer`'s `@Type()` do not work. You would carry `typedi`, `reflect-metadata` and the syntax while losing the only thing that makes them worth carrying — and the reference already builds every instance by hand with `new` in four registrars, so the container is doing almost nothing anyway.

Path aliases are asymmetric on purpose: `@/` in the frontend, because shadcn's Vite guide requires it and its components do not resolve without it; relative imports in the backend, as the reference mandates.

### 6. Scripts, the README, and CI

Three commands, not five:

```
pnpm install
pnpm run bootstrap     # docker compose up -d --wait, migrate, fetch models
pnpm dev               # pnpm -r --parallel
```

- **Not named `setup` or `init`** — both are pnpm's own commands, and `pnpm setup` configures pnpm itself, not your project. The README writes `pnpm run bootstrap` in full.
- **The model download is never a `postinstall`.** It would hide 1.5 GB inside `pnpm install`, and worse, pull it in CI where it is useless.
- **`docker compose up -d --wait`, not `up -d`.** Otherwise the migration races a Postgres that is still starting. The compose file therefore declares a healthcheck.

Scripts by owner: root has `bootstrap`, `dev`, `lint`, `format`, `typecheck`. `backend/` has `dev` (`tsx watch`), `db:up`, `db:generate`, `db:migrate`, `models:fetch`, and unit and integration suites split as in the reference. `frontend/` has what Vite ships.

Prerequisites for the README: Node 24, Docker, and pnpm — which is **not** currently installed on the owner's machine.

**CI runs `biome ci`, `tsc --noEmit`, and the unit tests. Nothing else.** No Docker, no database, no services. The standing rule behind it: **CI never downloads a model**, so the embedder ports are always mocked — which is also the reference's rule that only ports are mocked.

Integration tests are local only, by the owner's call. They must still run against a throwaway database via testcontainers, not against the development one: otherwise every run destroys the Files you ingested to try the app by hand.

**The cost, stated plainly:** nothing automated verifies the thing this product is judged on — whether the search returns the right thing. CI proves the code compiles, the style holds and the SQL does what it claims. Search quality stays judged by eye, as it was in [#7](https://github.com/javierponferradalopez/local-semantic-search/issues/7).

### Not decided here

- **Whether the contract is declared once or twice** is [#20](https://github.com/javierponferradalopez/local-semantic-search/issues/20), and it inherits a real price from today: if a Zod schema is to be the single declaration, with types from `z.infer`, then `contract/` stops being types-only and gains a dependency and a build step. Either the contract is written twice, or that package stops being free.
- **When models load and how they stay warm** is [#15](https://github.com/javierponferradalopez/local-semantic-search/issues/15).
- **The glossary is unchanged.** Every word used here is already in `CONTEXT.md`, and `FileStore` is a port name — implementation, not business language.

**Comment by javierponferradalopez** [comment]
Resolved. The arrangement is in the resolution comment above; the bounded-context split is ADR-0003 on master.
